### ISSUE TITLE
Suggestion: possible to reduce binary size (to 720 bytes)

### ISSUE THREAD

**Issue by tkchia** [AndreVallestero/minimal-efi-app#2]
Good day @AndreVallestero,

Thank you for this project.  In case it is useful, I have been able to reduce the size of `BOOTX64.EFI` from 2,560 bytes to 720 bytes, by changing the in-file section alignment (`lld-link` ... `-filealign:16` ...).  The `.EFI` file will still start, at least on my PC.

Thank you!

**Comment by AndreVallestero** [comment]
Thanks for letting me know! Does the option order matter? Is `lld-link -filealign:16 -subsystem:efi_application -nodefaultlib -dll -entry:efi_main main.o -out:BOOTX64.EFI` fine?

**Comment by tkchia** [comment]
Good day @AndreVallestero,

> Is `lld-link -filealign:16 -subsystem:efi_application -nodefaultlib -dll -entry:efi_main main.o -out:BOOTX64.EFI` fine?

Yes, that does work. :slightly_smiling_face:

The default setting (if `-filealign:`... is unspecified) is `-filealign:512`, which will mean that the data for each of the PE COFF sections in the binary must start at an offset which is a multiple of 512.

(I have heard that the 512-byte alignment is needed for Windows programs to work.  But apparently it is not needed for UEFI bootloaders.)

Thank you!
